[workspace]
resolver = "2"
members = [
    "examples/",
    "rend3",
    "rend3-anim",
    "rend3-egui",
    "rend3-framework",
    "rend3-gltf",
    "rend3-routine",
    "rend3-test",
    "rend3-types",
]

[profile.ci]
inherits = "dev"
debug = false
incremental = false

[profile.ci.package."*"]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true
lto = "thin"

#   Temporary override of out of date WGPU profiler
[patch.crates-io]
wgpu-profiler = { version = "^0.18.3", git = 'https://github.com/John-Nagle/wgpu-profiler' }
egui = { version = "0.29.1", git = 'https://github.com/emilk/egui.git'}
egui-wgpu = { version = "0.29.1", git = 'https://github.com/emilk/egui.git'}
epaint = { version = "0.29.1", git = 'https://github.com/emilk/egui.git' }
emath = { version = "0.29.1", git = 'git+https://github.com/emilk/egui.git' }
